application: dummy-application-name
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /PostAndFollowBack
  script: PostAndFollowBack.py
  login: admin
- url: /ReplyAndFav
  script: ReplyAndFav.py
  login: admin
- url: /.*
  static_files: index.html
  upload: index.html
